### ISSUE TITLE
Add `auth_plug`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#104]
At present while we've been rebuilding the MVP we've avoided Authentication for _speed_.
But to be a _useful_ MVP we _need_ to have Auth so that people can "own" their own `items`.
Thankfully, we've _comprehensively_ solved this problem before:
https://github.com/dwyl/phoenix-liveview-chat-example#12-authentication

# Todo 📝 

+ [ ] Borrow the code we've previously written.
+ [ ] Update the code in `lib/app_web/live/app_live.ex`
+ [ ] Update tests as necessary

**Comment by nelsonic** [comment]
Borrow [`auth_controller.ex`](https://raw.githubusercontent.com/dwyl/phoenix-liveview-chat-example/main/lib/liveview_chat_web/controllers/auth_controller.ex) from: https://raw.githubusercontent.com/dwyl/phoenix-liveview-chat-example/main/lib/liveview_chat_web/controllers/auth_controller.ex 

Got it working but test coverage still low ...

```sh
Finished in 0.7 seconds (0.2s async, 0.5s sync)
27 tests, 0 failures

Randomized with seed 534285
----------------
COV    FILE                                        LINES RELEVANT   MISSED
100.0% lib/app/item.ex                               246       33        0
100.0% lib/app/person.ex                              39        3        0
100.0% lib/app/timer.ex                               98       14        0
 12.5% lib/app_web/controllers/auth_controller.       37        8        7
 92.1% lib/app_web/live/app_live.ex                  209       63        5
 60.0% lib/app_web/router.ex                          22        5        2
100.0% lib/app_web/views/error_view.ex                16        1        0
[TOTAL]  89.0%
----------------
```
