### ISSUE TITLE
Always display timer even when no active timer is counting

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#106]
At present when a timer is stopped it disappears from the UI:
![mvp-timer-accumulation](https://user-images.githubusercontent.com/194400/179450760-f1f8242f-a43b-42ca-8534-26e27c001a37.gif)

This is lame because we cannot see how much time has been spent on a given item.
A much better UX would be to always have the time elapsed visible in the UI.

# Todo

+ [ ] Keep the timer visible when stopped
+ [ ] Change the button label to "**`Continue`** if there have been previous timers.
+ [ ] Avoid cluttering the  UI with an all-zeros timer i.e. should not be visible if no timers exist for an `item`

![image](https://user-images.githubusercontent.com/194400/179451059-5a263448-c6de-4563-b528-46d75ae70daa.png)

**Comment by nelsonic** [comment]
Working but style of stopped timer is not perfect:
https://user-images.githubusercontent.com/194400/179616684-9a7392b0-6ea6-44e4-89fc-7acb8b0d105e.mov

Good enough for MVP. 👍  (and by that I of course mean we'll "fix it in post!")
