### ISSUE TITLE
Clicking/Tapping the "done" Checkbox Should Stop Timer

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#107]
It's just occurred to me that clicking the checkbox to say an item is "done" does not stop the timer. 
Let's fix that! 

# Todo

+ [ ] create a function that looks for active timers for a given `item_id`
+ [ ] update the code in `handle_event("toggle")` event to stop the _active_ `timer` if there is one.
+ [ ] if there is no active timer (because some people will "do" a task without timing it 🙄) then ignore

**Comment by nelsonic** [comment]
Working with tests for both happy and unhappy path:    
![mvp-showing-checkbox-ends-timer](https://user-images.githubusercontent.com/194400/179715049-fc4f440a-bd41-44a9-9caa-74dc333feba5.gif)
 
_Finally_ going to work on `auth` now! #104
