### ISSUE TITLE
Top Nav

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#108]
In preparation for adding **`auth_plug`** #104 to allow people to save their data,
We need a way of showing people that:
a) they are _not_ currently logged in -> 
b) they _can_ login -> **`login`** button!
c) when they are logged in, an avatar
d) a logout button

So I'm thinking of doing a quick side-quest to add a responsive navigation bar to the top of the "page" (App)
as per the "crappy" [UI sketch](https://github.com/dwyl/app-mvp-phoenix/tree/phoenix-1.6-2022-refresh-issue-%2389#proposed-mvp-uiux) I made a while back:

![mvp-proposed-ux](https://user-images.githubusercontent.com/194400/73374277-d9445480-42b1-11ea-980a-3fabbfe5a9fd.png)

We currently already have a lot of this interface in place:  https://github.com/dwyl/app-mvp-phoenix/issues/89#issuecomment-1188810720

![mvp-showing-checkbox-ends-timer](https://user-images.githubusercontent.com/194400/179715049-fc4f440a-bd41-44a9-9caa-74dc333feba5.gif)

While we could _easily_ get away with adding **`auth_plug`** _without_ a nav or [logout button](https://github.com/dwyl/auth_plug/issues/11#issuecomment-961506177). 💭  
After all this is a "scrappy" MVP that doesn't _need_ to have the [bells and whistles](https://dictionary.cambridge.org/dictionary/english/bells-and-whistles) ... 🔔
We _want_ to have this [nice-to-have] feature so that we can start learning from and iterating on it. 📱 

# Todo

+ [ ] create a responsive fixed top nav using Tailwind CSS 
  + [ ] fixed so that it's always available for quick actions.
+ [ ] it should occupy the least amount of space possible
+ [ ] create it **`static`** over in https://github.com/dwyl/learn-tailwind so that it's generic/reusable 
+ [ ] bring it back to the MVP and add the ***`dynamic`*** elements

**Comment by nelsonic** [comment]
Logo:
```html
<a href="https://dwyl.com" class="flex items-center">
    <img src="https://dwyl.com/img/favicon-32x32.png" class="mr-3 h-6 sm:h-9" alt="dwyl logo">
</a>
```

**Comment by nelsonic** [comment]
Drawing inspiration from: https://flowbite.com/docs/components/navbar/

**Comment by nelsonic** [comment]
Reading: https://tailwindcss.com/docs/reusing-styles#loops

**Comment by nelsonic** [comment]
Basic Static Top Nav:

![image](https://user-images.githubusercontent.com/194400/179747998-a498deda-99f1-45d7-ba81-8832bdbf57ff.png)

**Comment by nelsonic** [comment]
Integrated into the App:

![image](https://user-images.githubusercontent.com/194400/179748370-2f5fdb8d-bee2-4bdc-ab01-1848ee52ed2a.png)

Full screen:

![image](https://user-images.githubusercontent.com/194400/179748441-38eb5906-bbaa-46e5-85be-b1acc33c1261.png)

Consider this done. ✅
