### ISSUE TITLE
BUG: New Person inserted each time I authenticate with Google

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#29]
Minor issue: the `App.Ctx.get_person_by_email` invoked in `google_auth_controller.ex`
does not do what we `expect` it to ... 
https://github.com/dwyl/app-mvp-phoenix/blob/5a9a0fddb2d908de48b2b4de9853dbcaef63a0e5/lib/app_web/controllers/google_auth_controller.ex#L15

This is _never_ going to work in a world where the `email` field is _encrypted_ ... 
(_i.e. each time the email address `c@t.com` is encrypted/inserted the ciphertext is different ..._)
https://github.com/dwyl/app-mvp-phoenix/blob/5a9a0fddb2d908de48b2b4de9853dbcaef63a0e5/lib/app/ctx.ex#L238

The result is that a **`new`** `person` record is inserted each time the person uses Google Auth:
![image](https://user-images.githubusercontent.com/194400/69998343-055f8580-154e-11ea-8537-c9dd2a12d4f5.png)

# 🙄 

# Todo 

+ [x] Ensure that the `people` schema has `field :email_hash, Fields.EmailHash` defined
  + [x] Confirm that all tests still pass after updating the field definition.
+ [x] modify the `App.Ctx.get_person_by_email/1` function to:
  + [x] Use `Fields.EmailHash.dump(email)` to _hash_ the email address _before_ attempting to look it up.
  + [x] Lookup an email by the **`email_hash`** _not the **`email`** (`Fields.EmailEncrypted`)_

```elixir
def get_person_by_email(email) do
  email_hash = Fields.EmailHash.dump(email)
  Repo.get_by(Person, email_hash: email_hash)
end 
```

**Comment by SimonLab** [comment]
> Confirm that all tests still pass after updating the field definition.

No they don't! 
![image](https://user-images.githubusercontent.com/6057298/70057115-7b0e3480-15d4-11ea-9af1-884c20294016.png)

Updating the tests now. Linked also to #25

**Comment by SimonLab** [comment]
> Use Fields.EmailHash.dump(email) to hash the email address before attempting to look it up.

We don't need to use `dump` as `EmailHash` field will use `cast` to convert the email to the hash before looking for it

**Comment by SimonLab** [comment]
The function `get_by_email` still returns `nil` when search on email_hash:
```
SELECT p0."id", p0."email", p0."email_hash", p0."familyName", p0."givenName", p0."locale", p0."password_hash", p0."picture", p0."username", p0."username_hash", p0."status", p0."tag", p0."key_id", p0."inserted_at", p0."updated_at" FROM "people" AS p0 WHERE (p0."email_hash" = $1) [<<35, 170, 210, 164, 226, 27, 120, 16, 40, 188, 159, 44, 154, 226, 106, 172, 17, 237, 33, 235, 188, 25, 243, 86, 120, 63, 191, 122, 61, 154, 118, 198>>]
```
I think the value are different between the hash converted and the actual value inseted in the database

**Comment by SimonLab** [comment]
I've updated the way we save the email_hash to be able to retrieve the person by email.
Another error is displayed when the Person already exists in the database:
```
function App.Ctx.Person.fetch/2 is undefined (App.Ctx.Person does not implement the Access behaviour)
```
I think this is due to some person data not defined and required on the index template

**Comment by nelsonic** [comment]
Hmm... can you share your screen? I'm on Zoom.

**Comment by SimonLab** [comment]
The email attribute wasn't pattern matched on the correct parameters. It was done on the `person` instead of `attrs`

```
 def google_changeset(profile, %{"email" => email} = attrs) do
    profile
    |> cast(attrs, [:email, :givenName, :familyName, :picture, :locale])
    |> validate_required([:email])
    |> put_change(:email_hash, email )
  end
```
This works however I'm wondering if there is a nicer/other way to extract the email directly from the changeset after `|> validate_required([:email])`

**Comment by SimonLab** [comment]
When a person already exists in the database we are only creating a new session then rendering the 

next error to resolve:
![image](https://user-images.githubusercontent.com/6057298/70138759-de599e80-1688-11ea-864f-f2f7b633b0f2.png)

**Comment by SimonLab** [comment]
Schemas don't have the Access Behaviour, so we can't access data with `[ ]`, ie `people["email"]` returns an error. Using `.` is fine, `people.email` will work.

**Comment by nelsonic** [comment]
@SimonLab good catch. thanks for fixing this. 👍

**Comment by nelsonic** [comment]
Using `auth_plug` + `auth` this is no longer an issue. #65
