### ISSUE TITLE
Add Auth (AuthPlug) to MVP

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#65]
Now that we have Auth working https://dwylauth.herokuapp.com 🚀  we can add it to the MVP to simplify the App.

# Todo

+ [x] Add `auth_plug` to `mix.exs` see: https://github.com/dwyl/auth_plug
+ [x] Enable `auth_plug` in `router.ex`
+ [x] Enable [`AuthPlugOptional`](https://github.com/dwyl/auth_plug#optional-auth) in `router.ex` for any routes where auth is optional
+ [x] Remove all personally identifiable information from the MVP
  + [x] Keep `people` table with bare minimum data to allow `FK` in `items` table to work.
+ [x] Remove any auth related tests and let `auth_plug` handle all of that!
+ [x] Ensure that everything still works as expected (_tests for creating `items` should all still pass_)
+ [x] Get back to building the features we _actually_ want! https://github.com/dwyl/app/issues/266

**Comment by nelsonic** [comment]
Before: http://localhost:4000/
![image](https://user-images.githubusercontent.com/194400/94660565-ba450900-02fd-11eb-9b07-58006bad7ace.png)

**Comment by nelsonic** [comment]
Tests pass as does UI:
![image](https://user-images.githubusercontent.com/194400/94842002-bce55280-0412-11eb-8541-ddebad0f5c13.png)

Need to decide what we're going to do with the home page:
![image](https://user-images.githubusercontent.com/194400/94842081-d9818a80-0412-11eb-96e4-f630e53eb44c.png)

I think it should immediately display the interface for inputting items.

**Comment by nelsonic** [comment]
Added `auth_plug` to MVP: #66
