### ISSUE TITLE
Render Counting Timer in UI with Alpine.js

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp-phoenix#99]
# Todo 

Using: https://github.com/dwyl/learn-alpine.js/blob/main/stopwatch.html as inspiration ...

+ [x] Render the timer element on the page using `Alpine.js` and use `LiveView` to sync between devices/clients
+ [x] Should display `hh:mm:ss` and count up one second at a time.
+ [x] Should use the `Timer.start` as the `start` time for the timer so that any new browsers/clients joining mid-way through a timer get the correct time.

**Comment by nelsonic** [comment]
@SimonLab we discussed this on our call today.
My reasoning for using `Alpine.js` is to make the code in the `app_live.html.heex` template as declarative as possible:

https://github.com/dwyl/app-mvp-phoenix/blob/a4dc98e37c96f4886c140e0ecf5fca9b10c0fd53/lib/app_web/live/app_live.html.heex#L48-L69

The Server Side code doesn't need to know anything about the UI/UX of Timers. 
The Server just knows the `Timer.start` and `Timer.end` data/values and the client can render them however it wants.

**Comment by nelsonic** [comment]
This is bugging me so I want to try and tackle it ... 🙄 
Basically we want to have the timer in the UI using the **`Timer.start`** value. 
and we want it to _continue_ running when new `items` are added.

Going to try and figure this out. But it will definitely be a "hack" as I'm not a [**`PETAL`**](https://github.com/dwyl/technology-stack/issues/87) expert by any means.

**Comment by nelsonic** [comment]
Instead of the "hack" I re-wrote the function and now we can have multiple timers running concurrently:

![image](https://user-images.githubusercontent.com/194400/179234895-0f6169d2-a4bb-4546-8922-309d4518f475.png)

I'm still refactoring some bits but confident it will all be working as expected very soon. 🧑‍💻

**Comment by nelsonic** [comment]
# Next: #103
